version: '3.8'

services:
  nojdstad-angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: nojdstad-angular-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production

