openapi: 3.0.0
info:
  title: Clean Pro UI API
  description: API to handle booking requests submitted from a form.
  version: "1.0.0"
servers:
  - url: /ui-api/v1
    description: Production server

paths:
  /submit-booking:
    post:
      summary: Submit a booking request
      operationId: submitBooking
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The booking request details as a formatted string.
              required:
                - message
      responses:
        '200':
          description: Successful booking submission
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Booking successfully submitted."
        '400':
          description: Invalid request (missing or malformed parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /submit-booking/structured:
    post:
      summary: Submit a structured booking request
      operationId: submitStructuredBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':
          description: Successful structured booking submission
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Structured booking successfully submitted."
        '400':
          description: Invalid request (missing or malformed parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        errorCode:
          type: string
          description: HTTP error code
          example: "400"
        message:
          type: string
          description: Error message explaining the issue
          example: "Invalid input. Please check your form fields and try again."

    BookingRequest:
      type: object
      properties:
        typeOfCleaningService:
          type: string
          description: Type of cleaning service
        preferredDate:
          type: string
          format: date
          description: Preferred date (yyyy-MM-dd)
        preferredTime:
          type: string
          format: time
          description: Preferred time (HH:mm)
        fullName:
          type: string
          description: Full name of the person
        emailAddress:
          type: string
          format: email
          description: Email address
        phoneNumber:
          type: string
          description: Phone number
        civicNumber:
          type: string
          description: Civic number for RUT-deduction
        address:
          type: string
          description: Address line
        apartment:
          type: string
          description: Apartment number
        postalCode:
          type: string
          description: Postal code
        city:
          type: string
          description: City
        otherInformation:
          type: string
          description: Additional information provided by the user
      required:
        - typeOfCleaningService
        - preferredDate
        - preferredTime
        - fullName
        - emailAddress
        - phoneNumber
        - civicNumber
        - address
        - postalCode
        - city